# Generated by Django 2.2.7 on 2019-11-05 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0002_auto_20191105_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showings', models.ManyToManyField(to='boxoffice.Showing')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxoffice.Theatre')),
            ],
        ),
        migrations.CreateModel(
            name='FullSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatreSchedules', models.ManyToManyField(to='boxoffice.TheatreSchedule')),
            ],
        ),
    ]
