# Generated by Django 2.2.7 on 2019-11-06 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxoffice', '0004_auto_20191106_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatreschedule',
            name='showings',
        ),
        migrations.RemoveField(
            model_name='theatreschedule',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='FullSchedule',
        ),
        migrations.DeleteModel(
            name='TheatreSchedule',
        ),
    ]
